<?php

/**
 * @file
 * Add 2 Numbers.
 * */

/**
 * Implement hook Form_alter().
 */
function add_number_form_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  if ($node->getType() == 'add_number') {
    $form['field_sum']['#access'] = FALSE;
    
    $form['field_status']['#access'] = FALSE;
    $form['#validate'][] = 'add_number_form_validate';
  }
}

/**
 * Implement hook form_validate().
 */
function add_number_form_validate($form, &$form_state) {
  $first_number = $form_state->getValue('field_first_number');
  $second_number = $form_state->getValue('field_second_number');
  if ($first_number[0]['value'] < 0) {
    $form_state->setErrorByName('field_first_number', t('First number Should be Greater Than 0'));
  }
  if ($second_number[0]['value'] < 0) {
    $form_state->setErrorByName('field_second_number', t('Second number Should be Greater Than 0'));
  }
  if (($first_number[0]['value']) == '') {
    $form_state->setErrorByName('field_first_number', t('Please Enter First number.'));
  }
  if (($second_number[0]['value']) == '') {
    $form_state->setErrorByName('field_second_number', t('Please Enter Second number.'));
  }
}

/**
 * Implement hook node_presave().
 */
function add_number_node_presave(&$node) {
  if ($node->getType() == 'add_number') {
    if ($node->isNew()) {
      $node->field_status->value = 'Created';
    }
    else {
      $node->field_status->value = 'Updated';
    }
    $first_number = $node->get('field_first_number')->getValue();
    $second_number = $node->get('field_second_number')->getValue();
    $sum = $first_number[0]['value'] + $second_number[0]['value'];
    $node->set('field_sum', $sum);
  }
}
